remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
domain: ie-diy.yuzhes.com
# title: Ireland Visa DIY
# description: DIY your Ireland Visa at minimal cost!
# show_downloads: true
# theme: jekyll-theme-minimal
